version: '2'
services:
  nanotid:
    build: ./Nanotid
    expose:
      - "80"
    ports:
      - "80:80"
    network_mode: host
    environment:
      - UDEV=1
    restart: always
    privileged: true
    devices:
      - "/dev:/dev"
    cap_add:
      - SYS_RAWIO
  minitid:
    build: ./Minitid
    expose:
      - "80"
      - "8888"
      - "8080"
    ports:
      - "80"
      - "8888:8888"
      - "8080:8080"
    network_mode: host
    environment:
      - UDEV=1
    restart: always
    privileged: true
    devices:
      - "/dev:/dev"
    cap_add:
      - SYS_RAWIO  
  euplotid:
    build: ./Euplotid
    expose:
      - "8894"
      - "8895"
    ports:
      - "8894:8894"
      - "8895:8895"
    network_mode: host
    environment:
      - UDEV=1
    restart: always
    privileged: true
    devices:
      - "/dev:/dev"
    cap_add:
      - SYS_RAWIO  