version: '2'
services:
  eugrow:
    build: ./Nanotid
    expose:
      - "80"
      - "8888"
    environment:
      - UDEV=1
    restart: always
    privileged: true
    tty: true
    network_mode: host
    devices:
      - "/dev:/dev"
    cap_add:
      - SYS_RAWIO