name: env
channels:
  - conda-forge
  - jetson-tx2
dependencies:
#  - conda-build
  - pip
  - python
  - setuptools
  - numpy
  - pip:
    - setuptools
    - gnureadline
    - plotly
    - pandas
    - dash
    - dash-html-components
    - dash-core-components
    - dash-renderer
    - flask
    - flask_sqlalchemy
    - APScheduler
    - gunicorn
    - jupyter
    - jupyterlab
#    - cmake
    - networkx
    - ipywidgets
    - Cython
#    - biopython
#    - pyliftover
#    - python-louvain
#    - pyyaml
#    - myvariant
#    - mygene
#    - pysam
#    - scikit-learn
#    - scipy
#    - scikit-build
#    - ninja
#    - lxml
#    - cffi
