name: env
channels:
  - conda-forge
  - bioconda
dependencies:
#  - conda-build
  - pip
  - python=3.8.*
  - setuptools
  - numpy
  - pip:
    - setuptools
    - gnureadline
    - plotly
    - pandas
    - dash
    - dash-html-components
    - dash-core-components
    - dash-renderer
    - flask
    - flask_sqlalchemy
    - APScheduler
    - gunicorn
    - jupyter
    - jupyterlab
#    - cmake
    - networkx
    - ipywidgets
    - Cython
    - https://developer.download.nvidia.com/compute/redist/jp/v51/pytorch/torch-1.14.0a0+44dac51c.nv23.01-cp38-cp38-linux_aarch64.whl
#    - visdom \
#    - tqdm \
#    - torchnet \
#    - torchvision \
#    - tensorboardx 
#    - biopython
#    - pyliftover
#    - python-louvain
#    - pyyaml
#    - myvariant
#    - mygene
#    - pysam
#    - scikit-learn
#    - scipy
#    - scikit-build
#    - ninja
#    - lxml
#    - cffi
