name: env
channels:
  - conda-forge
  - rpi
dependencies:
#  - conda-build
  - pip
  - python
  - setuptools
  - pip:
    - numpy
    - setuptools
    - gnureadline
    - adafruit-circuitpython-ssd1306
    - adafruit-circuitpython-framebuf
    - adafruit-circuitpython-rfm9x
    - adafruit-circuitpython-tinylora
    - plotly
    - pandas
    - rpi-rf
    - dash
    - dash-html-components
    - dash-core-components
    - dash-renderer
    - flask
    - flask_sqlalchemy
    - cffi
    - APScheduler
    - gunicorn
    - jupyter
    - jupyterlab